"""Build manifests/reciters.json and manifests/surahs.json from the 2026-08-25 survey.

This is a one-time authoring script, kept so the registry is reproducible and
reviewable. Re-run it only when the survey data or the slug table changes.
"""

from __future__ import annotations

import json
import pathlib
import sys

ROOT = pathlib.Path(__file__).resolve().parents[1]
SURVEY = ROOT / "manifests" / "upstream-folders.psv"
OUT_RECITERS = ROOT / "manifests" / "reciters.json"
OUT_SURAHS = ROOT / "manifests" / "surahs.json"
CHAPTERS = pathlib.Path(sys.argv[1]) if len(sys.argv) > 1 else None

# source folder -> (slug, display name, reciter key, style, riwayah, language, kind, notes)
# style: murattal | mujawwad | muallim | unknown
# kind: recitation | translation | mixed
TABLE = {
    "AbdulSamad_64kbps_QuranExplorer.Com": ("abdulsamad-quranexplorer-64kbps", "Abdul Basit Abdus-Samad (QuranExplorer.com edition)", "abdul-basit", "murattal", "hafs", "ar", "recitation", "Upstream readme: errors reported from Surah 2 ayah 22 onward."),
    "Abdul_Basit_Mujawwad_128kbps": ("abdul-basit-mujawwad-128kbps", "Abdul Basit Abdus-Samad, Mujawwad", "abdul-basit", "mujawwad", "hafs", "ar", "recitation", ""),
    "Abdul_Basit_Murattal_192kbps": ("abdul-basit-murattal-192kbps", "Abdul Basit Abdus-Samad, Murattal", "abdul-basit", "murattal", "hafs", "ar", "recitation", ""),
    "Abdul_Basit_Murattal_64kbps": ("abdul-basit-murattal-64kbps", "Abdul Basit Abdus-Samad, Murattal", "abdul-basit", "murattal", "hafs", "ar", "recitation", ""),
    "Abdullaah_3awwaad_Al-Juhaynee_128kbps": ("abdullah-awad-al-juhani-128kbps", "Abdullah Awad Al-Juhani", "abdullah-al-juhani", "murattal", "hafs", "ar", "recitation", ""),
    "Abdullah_Basfar_192kbps": ("abdullah-basfar-192kbps", "Abdullah Basfar", "abdullah-basfar", "murattal", "hafs", "ar", "recitation", "No 000_checksum.md5 upstream; verified by exact size, hashes generated by Maqra."),
    "Abdullah_Basfar_32kbps": ("abdullah-basfar-32kbps", "Abdullah Basfar", "abdullah-basfar", "murattal", "hafs", "ar", "recitation", ""),
    "Abdullah_Basfar_64kbps": ("abdullah-basfar-64kbps", "Abdullah Basfar", "abdullah-basfar", "murattal", "hafs", "ar", "recitation", ""),
    "Abdullah_Matroud_128kbps": ("abdullah-matroud-128kbps", "Abdullah Matroud", "abdullah-matroud", "murattal", "hafs", "ar", "recitation", ""),
    "Abdurrahmaan_As-Sudais_192kbps": ("abdurrahman-as-sudais-192kbps", "Abdurrahman As-Sudais", "as-sudais", "murattal", "hafs", "ar", "recitation", ""),
    "Abdurrahmaan_As-Sudais_64kbps": ("abdurrahman-as-sudais-64kbps", "Abdurrahman As-Sudais", "as-sudais", "murattal", "hafs", "ar", "recitation", ""),
    "Abu_Bakr_Ash-Shaatree_128kbps": ("abu-bakr-ash-shatri-128kbps", "Abu Bakr Ash-Shatri", "ash-shatri", "murattal", "hafs", "ar", "recitation", ""),
    "Abu_Bakr_Ash-Shaatree_64kbps": ("abu-bakr-ash-shatri-64kbps", "Abu Bakr Ash-Shatri", "ash-shatri", "murattal", "hafs", "ar", "recitation", ""),
    "Ahmed_Neana_128kbps": ("ahmed-neana-128kbps", "Ahmed Neana", "ahmed-neana", "murattal", "hafs", "ar", "recitation", ""),
    "Ahmed_ibn_Ali_al-Ajamy_128kbps_ketaballah.net": ("ahmed-al-ajmi-128kbps-ketaballah", "Ahmed ibn Ali Al-Ajmi (KetabAllah.net edition)", "ahmed-al-ajmi", "murattal", "hafs", "ar", "recitation", ""),
    "Ahmed_ibn_Ali_al-Ajamy_64kbps_QuranExplorer.Com": ("ahmed-al-ajmi-64kbps-quranexplorer", "Ahmed ibn Ali Al-Ajmi (QuranExplorer.com edition)", "ahmed-al-ajmi", "murattal", "hafs", "ar", "recitation", ""),
    "ahmed_ibn_ali_al_ajamy_128kbps": ("ahmed-al-ajmi-128kbps", "Ahmed ibn Ali Al-Ajmi", "ahmed-al-ajmi", "murattal", "hafs", "ar", "recitation", ""),
    "Akram_AlAlaqimy_128kbps": ("akram-al-alaqimi-128kbps", "Akram Al-Alaqimi", "akram-al-alaqimi", "murattal", "hafs", "ar", "recitation", ""),
    "Alafasy_128kbps": ("mishari-alafasy-128kbps", "Mishari Rashid Alafasy", "alafasy", "murattal", "hafs", "ar", "recitation", ""),
    "Alafasy_64kbps": ("mishari-alafasy-64kbps", "Mishari Rashid Alafasy", "alafasy", "murattal", "hafs", "ar", "recitation", ""),
    "Ali_Hajjaj_AlSuesy_128kbps": ("ali-hajjaj-al-suwaisi-128kbps", "Ali Hajjaj Al-Suwaisi", "ali-hajjaj-al-suwaisi", "murattal", "hafs", "ar", "recitation", ""),
    "Ali_Jaber_64kbps": ("ali-jaber-64kbps", "Ali Jaber", "ali-jaber", "murattal", "hafs", "ar", "recitation", ""),
    "Ayman_Sowaid_64kbps": ("ayman-swaid-64kbps", "Ayman Swaid", "ayman-swaid", "murattal", "hafs", "ar", "recitation", "No checksum file and no zip upstream; loose files only."),
    "aziz_alili_128kbps": ("aziz-alili-128kbps", "Aziz Alili", "aziz-alili", "murattal", "hafs", "ar", "recitation", "Ships its own 000_timings.zip upstream."),
    "Fares_Abbad_64kbps": ("fares-abbad-64kbps", "Fares Abbad", "fares-abbad", "murattal", "hafs", "ar", "recitation", ""),
    "Ghamadi_40kbps": ("saad-al-ghamdi-40kbps", "Saad Al-Ghamdi", "saad-al-ghamdi", "murattal", "hafs", "ar", "recitation", "Only 000_unverified_checksum.md5 upstream."),
    "Hani_Rifai_192kbps": ("hani-ar-rifai-192kbps", "Hani Ar-Rifai", "hani-ar-rifai", "murattal", "hafs", "ar", "recitation", ""),
    "Hani_Rifai_64kbps": ("hani-ar-rifai-64kbps", "Hani Ar-Rifai", "hani-ar-rifai", "murattal", "hafs", "ar", "recitation", ""),
    "Hudhaify_128kbps": ("ali-al-hudhaifi-128kbps", "Ali Al-Hudhaifi", "ali-al-hudhaifi", "murattal", "hafs", "ar", "recitation", "Only 000_unverified_checksum.md5 and md5.sum upstream."),
    "Hudhaify_32kbps": ("ali-al-hudhaifi-32kbps", "Ali Al-Hudhaifi", "ali-al-hudhaifi", "murattal", "hafs", "ar", "recitation", ""),
    "Hudhaify_64kbps": ("ali-al-hudhaifi-64kbps", "Ali Al-Hudhaifi", "ali-al-hudhaifi", "murattal", "hafs", "ar", "recitation", ""),
    "Husary_128kbps": ("mahmoud-al-husary-murattal-128kbps", "Mahmoud Khalil Al-Husary, Murattal", "al-husary", "murattal", "hafs", "ar", "recitation", ""),
    "Husary_128kbps_Mujawwad": ("mahmoud-al-husary-mujawwad-128kbps", "Mahmoud Khalil Al-Husary, Mujawwad", "al-husary", "mujawwad", "hafs", "ar", "recitation", ""),
    "Husary_64kbps": ("mahmoud-al-husary-murattal-64kbps", "Mahmoud Khalil Al-Husary, Murattal", "al-husary", "murattal", "hafs", "ar", "recitation", ""),
    "Husary_Muallim_128kbps": ("mahmoud-al-husary-muallim-128kbps", "Mahmoud Khalil Al-Husary, Muallim (teaching recitation)", "al-husary", "muallim", "hafs", "ar", "recitation", ""),
    "Husary_Mujawwad_64kbps": ("mahmoud-al-husary-mujawwad-64kbps", "Mahmoud Khalil Al-Husary, Mujawwad", "al-husary", "mujawwad", "hafs", "ar", "recitation", ""),
    "Ibrahim_Akhdar_32kbps": ("ibrahim-al-akhdar-32kbps", "Ibrahim Al-Akhdar", "ibrahim-al-akhdar", "murattal", "hafs", "ar", "recitation", ""),
    "Karim_Mansoori_40kbps": ("karim-mansouri-40kbps", "Karim Mansouri", "karim-mansouri", "murattal", "hafs", "ar", "recitation", "Upstream details: downloaded pre-split from islam4u.com."),
    "Khaalid_Abdullaah_al-Qahtaanee_192kbps": ("khalid-al-qahtani-192kbps", "Khalid Abdullah Al-Qahtani", "khalid-al-qahtani", "murattal", "hafs", "ar", "recitation", ""),
    "khalefa_al_tunaiji_64kbps": ("khalifa-al-tunaiji-64kbps", "Khalifa Al-Tunaiji", "khalifa-al-tunaiji", "murattal", "hafs", "ar", "recitation", ""),
    "MaherAlMuaiqly128kbps": ("maher-al-muaiqly-128kbps", "Maher Al-Muaiqly", "maher-al-muaiqly", "murattal", "hafs", "ar", "recitation", "Upstream info.txt (Zekr project, 2010): recitation license UNKNOWN."),
    "Maher_AlMuaiqly_64kbps": ("maher-al-muaiqly-64kbps", "Maher Al-Muaiqly", "maher-al-muaiqly", "murattal", "hafs", "ar", "recitation", ""),
    "mahmoud_ali_al_banna_32kbps": ("mahmoud-ali-al-banna-32kbps", "Mahmoud Ali Al-Banna", "mahmoud-ali-al-banna", "murattal", "hafs", "ar", "recitation", ""),
    "Menshawi_16kbps": ("mohamed-siddiq-al-minshawi-16kbps", "Mohamed Siddiq Al-Minshawi", "al-minshawi", "unknown", "hafs", "ar", "recitation", ""),
    "Menshawi_32kbps": ("mohamed-siddiq-al-minshawi-32kbps", "Mohamed Siddiq Al-Minshawi", "al-minshawi", "unknown", "hafs", "ar", "recitation", "Incomplete upstream: 303 ayah files missing. Only 000_unverified_checksum.md5."),
    "Minshawy_Mujawwad_192kbps": ("mohamed-siddiq-al-minshawi-mujawwad-192kbps", "Mohamed Siddiq Al-Minshawi, Mujawwad", "al-minshawi", "mujawwad", "hafs", "ar", "recitation", ""),
    "Minshawy_Mujawwad_64kbps": ("mohamed-siddiq-al-minshawi-mujawwad-64kbps", "Mohamed Siddiq Al-Minshawi, Mujawwad", "al-minshawi", "mujawwad", "hafs", "ar", "recitation", ""),
    "Minshawy_Murattal_128kbps": ("mohamed-siddiq-al-minshawi-murattal-128kbps", "Mohamed Siddiq Al-Minshawi, Murattal", "al-minshawi", "murattal", "hafs", "ar", "recitation", ""),
    "Minshawy_Teacher_128kbps": ("mohamed-siddiq-al-minshawi-muallim-128kbps", "Mohamed Siddiq Al-Minshawi, Muallim (teaching recitation)", "al-minshawi", "muallim", "hafs", "ar", "recitation", "Present on the server but listed nowhere on everyayah.com."),
    "Mohammad_al_Tablaway_128kbps": ("mohammad-al-tablawi-128kbps", "Mohammad Al-Tablawi", "mohammad-al-tablawi", "murattal", "hafs", "ar", "recitation", ""),
    "Mohammad_al_Tablaway_64kbps": ("mohammad-al-tablawi-64kbps", "Mohammad Al-Tablawi", "mohammad-al-tablawi", "murattal", "hafs", "ar", "recitation", ""),
    "Muhammad_AbdulKareem_128kbps": ("muhammad-abdul-kareem-128kbps", "Muhammad Abdul-Kareem", "muhammad-abdul-kareem", "murattal", "hafs", "ar", "recitation", ""),
    "Muhammad_Ayyoub_128kbps": ("muhammad-ayyub-128kbps", "Muhammad Ayyub", "muhammad-ayyub", "murattal", "hafs", "ar", "recitation", ""),
    "Muhammad_Ayyoub_32kbps": ("muhammad-ayyub-32kbps", "Muhammad Ayyub", "muhammad-ayyub", "murattal", "hafs", "ar", "recitation", "Only 000_unverified_checksum.md5 upstream."),
    "Muhammad_Ayyoub_64kbps": ("muhammad-ayyub-64kbps", "Muhammad Ayyub", "muhammad-ayyub", "murattal", "hafs", "ar", "recitation", ""),
    "Muhammad_Jibreel_128kbps": ("muhammad-jibril-128kbps", "Muhammad Jibril", "muhammad-jibril", "murattal", "hafs", "ar", "recitation", ""),
    "Muhammad_Jibreel_64kbps": ("muhammad-jibril-64kbps", "Muhammad Jibril", "muhammad-jibril", "murattal", "hafs", "ar", "recitation", ""),
    "Muhsin_Al_Qasim_192kbps": ("muhsin-al-qasim-192kbps", "Muhsin Al-Qasim", "muhsin-al-qasim", "murattal", "hafs", "ar", "recitation", ""),
    "Mustafa_Ismail_48kbps": ("mustafa-ismail-48kbps", "Mustafa Ismail", "mustafa-ismail", "unknown", "hafs", "ar", "recitation", "Incomplete upstream: 2017 of 6236 ayah files present (4219 missing). No checksum file."),
    "Nabil_Rifa3i_48kbps": ("nabil-ar-rifai-48kbps", "Nabil Ar-Rifai", "nabil-ar-rifai", "murattal", "hafs", "ar", "recitation", "Upstream details: provided by Ebrahim Badiee, Shiraz, 2019-2020. No checksum file, no zip."),
    "Nasser_Alqatami_128kbps": ("nasser-al-qatami-128kbps", "Nasser Al-Qatami", "nasser-al-qatami", "murattal", "hafs", "ar", "recitation", ""),
    "Parhizgar_48kbps": ("parhizgar-48kbps", "Parhizgar", "parhizgar", "murattal", "hafs", "ar", "recitation", "recitations.js labels this entry Parhizgar_64Kbps; the folder says 48kbps."),
    "Sahl_Yassin_128kbps": ("sahl-yassin-128kbps", "Sahl Yassin", "sahl-yassin", "murattal", "hafs", "ar", "recitation", ""),
    "Salaah_AbdulRahman_Bukhatir_128kbps": ("salah-bukhatir-128kbps", "Salah Abdurrahman Bukhatir", "salah-bukhatir", "murattal", "hafs", "ar", "recitation", ""),
    "Salah_Al_Budair_128kbps": ("salah-al-budair-128kbps", "Salah Al-Budair", "salah-al-budair", "murattal", "hafs", "ar", "recitation", ""),
    "Saood_ash-Shuraym_128kbps": ("saud-ash-shuraim-128kbps", "Saud Ash-Shuraim", "saud-ash-shuraim", "murattal", "hafs", "ar", "recitation", "Only 000_unverified_checksum.md5 and Shuray_md5.sum upstream."),
    "Saood_ash-Shuraym_64kbps": ("saud-ash-shuraim-64kbps", "Saud Ash-Shuraim", "saud-ash-shuraim", "murattal", "hafs", "ar", "recitation", ""),
    "Yaser_Salamah_128kbps": ("yasser-salamah-128kbps", "Yasser Salamah", "yasser-salamah", "murattal", "hafs", "ar", "recitation", ""),
    "Yasser_Ad-Dussary_128kbps": ("yasser-ad-dossari-128kbps", "Yasser Ad-Dossari", "yasser-ad-dossari", "murattal", "hafs", "ar", "recitation", ""),
    "English/Sahih_Intnl_Ibrahim_Walk_192kbps": ("en-sahih-international-ibrahim-walk-192kbps", "English translation (Sahih International) read by Ibrahim Walk", "ibrahim-walk", "unknown", "hafs", "en", "translation", "Spoken English translation, one file per ayah."),
    "MultiLanguage/Basfar_Walk_192kbps": ("ar-en-basfar-walk-192kbps", "Abdullah Basfar (Arabic) with Ibrahim Walk (English translation)", "abdullah-basfar", "murattal", "hafs", "ar+en", "mixed", "Each file carries the Arabic ayah followed by its English translation."),
    "translations/Fooladvand_Hedayatfar_40Kbps": ("fa-fooladvand-hedayatfar-40kbps", "Persian translation (Fooladvand) read by Hedayatfar", "hedayatfar", "unknown", "hafs", "fa", "translation", ""),
    "translations/Makarem_Kabiri_16Kbps": ("fa-makarem-kabiri-16kbps", "Persian translation (Makarem) read by Kabiri", "kabiri", "unknown", "hafs", "fa", "translation", ""),
    "translations/azerbaijani/balayev": ("az-balayev", "Azerbaijani translation read by Balayev", "balayev", "unknown", "hafs", "az", "translation", "Bitrate not stated in the folder name; recitations.js says 64Kbps."),
    "translations/besim_korkut_ajet_po_ajet": ("bs-besim-korkut-128kbps", "Bosnian translation (Besim Korkut), ayah by ayah", "besim-korkut", "unknown", "hafs", "bs", "translation", "Upstream details: readers Tarik Heli and Izudin Bajrovic, prepared by Dar Al Kuran, Mostar."),
    "translations/urdu_farhat_hashmi": ("ur-farhat-hashmi-32kbps", "Urdu word-for-word translation by Farhat Hashmi", "farhat-hashmi", "unknown", "hafs", "ur", "translation", "Folder carries 44 lesson-note text files and its own timings subfolder."),
    "translations/urdu_shamshad_ali_khan_46kbps": ("ur-shamshad-ali-khan-46kbps", "Urdu translation read by Shamshad Ali Khan", "shamshad-ali-khan", "unknown", "hafs", "ur", "translation", ""),
    "warsh/warsh_Abdul_Basit_128kbps": ("warsh-abdul-basit-128kbps", "Abdul Basit Abdus-Samad, Warsh", "abdul-basit", "murattal", "warsh", "ar", "recitation", "Incomplete upstream: 6214 ayah files present (everyayah.com reports 47 missing)."),
    "warsh/warsh_ibrahim_aldosary_128kbps": ("warsh-ibrahim-al-dosari-128kbps", "Ibrahim Al-Dosari, Warsh", "ibrahim-al-dosari", "murattal", "warsh", "ar", "recitation", ""),
    "warsh/warsh_yassin_al_jazaery_64kbps": ("warsh-yassin-al-jazairi-64kbps", "Yassin Al-Jazairi, Warsh", "yassin-al-jazairi", "murattal", "warsh", "ar", "recitation", ""),
}

EXCLUDED = {
    "Abu Bakr Ash-Shaatree_128kbps": "Byte-identical duplicate of Abu_Bakr_Ash-Shaatree_128kbps (same file count and sizes); the underscore folder is the one everyayah.com links to.",
    "Saood bin Ibraaheem Ash-Shuraym_128kbps": "Duplicate of Saood_ash-Shuraym_128kbps with one extra stray file; the underscore folder is the one everyayah.com links to.",
    "English/Ibrahim_Walk_192kbps_TEST": "Duplicate of English/Sahih_Intnl_Ibrahim_Walk_192kbps (same file count and sizes).",
    "translations/bosnian/besim_korkut_ajet_po_ajet_audio": "Duplicate of translations/besim_korkut_ajet_po_ajet (same file count and sizes), without checksum or zip.",
    "Ibrahim_Akhdar_64kbps": "Empty upstream: no ayah files, and 000_versebyverse.zip is 527 bytes. everyayah.com itself reports 6236 files missing.",
    "MultiLanguage/Shaatree_Walk_64kbps": "No per-ayah files; only a 1 GB offline zip of unknown internal layout. Mirrored verbatim under extras, not as a reciter set.",
}


def parse_bitrate(folder: str) -> int | None:
    import re
    m = re.search(r"(\d{2,3})\s*[kK]bps", folder)
    return int(m.group(1)) if m else None


def main() -> None:
    rows = {}
    for line in SURVEY.read_text(encoding="utf-8").splitlines():
        if not line.strip() or line.startswith("#"):
            continue
        folder, mp3, mp3mb, zipmb, dirs, other = line.split("|", 5)
        rows[folder] = {
            "ayah_files_seen": int(mp3),
            "ayah_files_mib_approx": int(mp3mb),
            "zip_mib_approx": int(zipmb),
            "subfolders": [d for d in dirs.split("+") if d],
            "other_files": [o for o in other.split("+") if o],
        }

    missing = set(TABLE) - set(rows)
    extra = set(rows) - set(TABLE) - set(EXCLUDED)
    if missing or extra:
        raise SystemExit(f"table/survey mismatch: missing={sorted(missing)} extra={sorted(extra)}")

    reciters = []
    for folder, (slug, name, key, style, riwayah, lang, kind, notes) in TABLE.items():
        r = rows[folder]
        other_names = [o.split("=")[0] for o in r["other_files"]]
        checksum_files = [n for n in other_names if n.lower().endswith((".md5", ".sum")) or n in ("md5sum.txt",)]
        expected = 6236
        if r["ayah_files_seen"] >= 6236:
            status = "complete"
        else:
            status = "incomplete"
        reciters.append({
            "slug": slug,
            "name": name,
            "reciter_key": key,
            "style": style,
            "riwayah": riwayah,
            "language": lang,
            "kind": kind,
            "bitrate_kbps": parse_bitrate(folder),
            "source_folder": folder,
            "source_url": "https://everyayah.com/data/" + "/".join(
                __import__("urllib.parse").parse.quote(p) for p in folder.split("/")) + "/",
            "upstream_checksum_files": checksum_files,
            "upstream_zip": "000_versebyverse.zip" if "000_versebyverse.zip" in other_names else None,
            "upstream_subfolders": r["subfolders"],
            "survey_2026_08_25": {
                "ayah_files_seen": r["ayah_files_seen"],
                "ayah_files_mib_approx": r["ayah_files_mib_approx"],
                "zip_mib_approx": r["zip_mib_approx"],
            },
            "status": status,
            "notes": notes,
            "github_release_tag": slug,
            "huggingface_repo": f"maqra-project/{slug}",
        })

    excluded = [{"source_folder": f, "reason": why} for f, why in EXCLUDED.items()]

    doc = {
        "$schema_version": 1,
        "generated_from": "manual survey of https://everyayah.com/data/ on 2026-08-25",
        "ayah_file_pattern": "SSSAAA.mp3 (surah 3 digits, ayah 3 digits); AAA=000 is the basmala or isti'adhah intro file where a folder has one",
        "count": len(reciters),
        "reciters": reciters,
        "excluded_upstream_folders": excluded,
    }
    OUT_RECITERS.write_text(json.dumps(doc, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    if CHAPTERS:
        ch = json.loads(CHAPTERS.read_text(encoding="utf-8"))
        assert len(ch) == 114 and sum(c["total_verses"] for c in ch) == 6236
        surahs = [{
            "number": c["id"],
            "name_ar": c["name"],
            "name_en": c["transliteration"],
            "ayah_count": c["total_verses"],
            "revelation": c["type"],
        } for c in ch]
        OUT_SURAHS.write_text(json.dumps({
            "$schema_version": 1,
            "source": "risan/quran-json dist/chapters/index.json (fetched 2026-08-25); ayah counts cross-checked against everyayah.com recitations.js ayahCount, zero differences",
            "total_ayahs": 6236,
            "surahs": surahs,
        }, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")

    print(f"wrote {len(reciters)} reciters, {len(excluded)} excluded")


if __name__ == "__main__":
    main()
